### ISSUE TITLE
Wrong pin for OLED CS in alternate wiring for ProMicro 5V

### ISSUE THREAD

**Issue by sgoetze** [MrBlinky/Arduboy-homemade-package#1]
In line 44 of Arduino2Core.h is a typing mistake:

#define PIN_CS 3     for PORTD3 Pin - it has to be #define PIN_CS 1

Thank you for your work that helps me much to make my grandchildren happy with a homemade Arduboy.

**Comment by MrBlinky** [comment]
I sure did! Thanks for telling me. I'll fix it in the next update and good to hear the package is helpful.

**Comment by MrBlinky** [comment]
Fixed in update
