### ISSUE TITLE
Is there possibility to add support for screen with SSH1106 over i2c ?

### ISSUE THREAD

**Issue by GamerClassN7** [MrBlinky/Arduboy-homemade-package#11]
Hi,
Is there possibility to add support for screen with SSH1106 over i2c ?
thank you in advance for answer

**Comment by GamerClassN7** [comment]
When i use:
![image](https://user-images.githubusercontent.com/22167469/106728467-c4a94380-660c-11eb-91c0-31817351217f.png)
i get at leas some rubbish's but at leas something and sometimes there is even some input :)
![IMG_20210203_103034043.jpg](https://user-images.githubusercontent.com/22167469/106727712-08e81400-660c-11eb-9a61-87ef974e9185.jpg)

**Comment by GamerClassN7** [comment]
IT IS MOST COMMON oled IN MY COUNTRY
LINK TO DATASHEED https://drive.google.com/file/d/19hxmIwuuTNxKzC-OcNMQJkltGV3B0DgB/view

**Comment by MrBlinky** [comment]
I'll look into your request. I see you’ve also asked the same question in [Arduboy Community](https://community.arduboy.com/t/ssh1106-i2c/9583). Please continue communication there.

**Comment by GamerClassN7** [comment]
@MrBlinky  i added required information to Arduboy Community. :)

**Comment by MrBlinky** [comment]
Support for SH1106 I2C display added
