### ISSUE TITLE
Using the 1106 screen making machine, the game package is burned, but it displays garbled code

### ISSUE THREAD

**Issue by Kiwano-Demo** [MrBlinky/Arduboy-homemade-package#13]
Hello, I have a question about arduboy screen driver? I used the 1106 screen. During the burning guide, I specially selected the 1106 display, and the burning was successful; But after I burned the game package for the game console, my game was messy, and the boot menu was normal; What can I do to solve it? I learned from other friends that I can only use 1306 screen, because the game hex file has compiled 1306.

**Comment by MrBlinky** [comment]
Make sure the Arduboy2 library was not installed manually. If it was then remove it from the sketchbook library folder.

Try uploading the Arduboy2 Hello World example and see if that functions properly. If it does and your game doesn't then  that game probably uses it's own (modified) Arduboy2 library and requires manual changes to make it to work.

If the Hello World sketch still produces a 'messy' display then check the display wiring.
