### ISSUE TITLE
Bring out A5 on expansion connector

### ISSUE THREAD

**Issue by MLXXXp** [MrBlinky/Arduboy-homemade-package#5]
Suggestion:
Pin 8 on the expansion connector is currently assigned as:
`Not connected (reserved for future use)`

I suggest specifying it as Arduino Pin A5. This pin is not used on the Arduboy but is brought out as a pad on the back of the circuit board.

Having an analogue input would allow potentiometer based paddles or other variable voltage devices to be more easily interfaced. Having only one analogue input might be a bit limiting but it could be expanded using an analogue multiplexor IC, controlled by I²C, SPI or digital.

Of course, A5 could also be used for general purpose digital I/O or as another CS for SPI.

**Comment by MrBlinky** [comment]
I wasn't sure what to hook to the unused pin yet. But A5 makes the most sense. (easy accessible and an analog input) I'll adapt the documentation.

**Comment by MLXXXp** [comment]
You may wish to note in the documentation that A5 isn't available as a brought out pin on a standard Pro Micro.

**Comment by MrBlinky** [comment]
Good point. Added.
